src/Entity/Demande.php
<?php

namespace App\Entity;

use App\Repository\DemandeRepository;
use Doctrine\DBAL\Types\Types;
use Gedmo\Mapping\Annotation as Gedmo; // gedmo annotations
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DemandeRepository::class)]
class Demande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length:300 , type: Types::TEXT)]
    #[Assert\NotBlank(message: 'Veuillez renseigner le motif ')]
    private ?string $motif = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: 'Veuillez renseigner la date de la rencontre')]
    #[Assert\Expression("this.getCreatedAt() <= this.getDaterencontre()", message: "la date de la rencontre doit être superirieure ou égale à la date de création")]

    private ?\DateTimeInterface $daterencontre = null;
    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Veuillez renseigner le lieu d'habitation")]
    private ?string $lieu_habitation = null;

    #[ORM\Column(length: 16)]
    #[Assert\NotBlank(message: 'Veuillez renseigner le numéro')]
    #[Assert\Length(
        min: 10,
        max: 16,
        minMessage: 'Le numéro de téléphone doit faire au moins {{ limit }} caractères',
        maxMessage: 'Le numéro de téléphone ne doit pas faire plus de {{ limit }} caractères'
    )]
    private ?string $numero = null;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    #[ORM\JoinColumn(nullable: true)]
    #[Assert\NotBlank(message: 'Veuillez selectionner des la communaute')]
    private ?Communaute $communaute = null;

    #[ORM\Column(nullable: true, type: Types::TEXT)]
    private ?string $justification = null;
    
    #[ORM\Column(length: 255)]
    private ?string $etat = 'demande_initie' ;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    #[Gedmo\Blameable(on: 'create')]
    private ?Utilisateur $utilisateur = null;



    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'update')]
    private ?\DateTimeInterface $UpdatedAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeInterface $CreatedAt = null;
 
    public function getDaterencontre(): ?\DateTimeInterface
    {
        return $this->daterencontre;
    }

    public function setDaterencontre(\DateTimeInterface $daterencontre): self
    {
        $this->daterencontre = $daterencontre;

        return $this;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    
    public function getLieuHabitation(): ?string
    {
        return $this->lieu_habitation;
    }

    public function setLieuHabitation(string $lieu_habitation): self
    {
        $this->lieu_habitation = $lieu_habitation;

        return $this;
    }
    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getCommunaute(): ?Communaute
    {
        return $this->communaute;
    }

    public function setCommunaute(?Communaute $communaute): self
    {
        $this->communaute = $communaute;

        return $this;
    }
    public function getJustification(): ?string
    {
        return $this->justification;
    }

    public function setJustification(string $justification): self
    {
        $this->justification = $justification;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }


    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function __toString()
    {
        if (is_null($this->communaute)) {
            return 'NULL';
        }
        return $this->communaute;
    }

    public function getDate()
    {
        // Créer un objet DateTime à partir de la chaîne de date fournie
        $date = $this->daterencontre;
        $format = 'Y-m-d';

        // Formater la date selon le format spécifié
        $formattedDate = $date->format($format);

        return $formattedDate;
    }
}

src/Controller/Configuration/Statistique/DashboadController.php
<?php

namespace App\Controller\Configuration\Statistique;

use App\Service\Utils;
use App\Entity\Audience;
use App\Entity\Localite;
use App\Entity\Categorie;
use App\Entity\Communaute;
use App\Service\ActionRender;
use App\Service\StatsService;
use Doctrine\ORM\QueryBuilder;
use App\Controller\BaseController;
use App\Repository\EmployeRepository;
use App\Repository\CommunauteRepository;
use finfo;
use Symfony\Component\HttpFoundation\Request;
use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTableFactory;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/dashboard')]
class DashboadController extends BaseController
{
    
    
    private function createFilterForm()
    {

        $formBuilder = $this->createFormBuilder()
            ->setAction($this->generateUrl('app_config_statistique_index'))
            ->setMethod('POST');

        $formBuilder->add('tranche', ChoiceType::class, [
            'label' => 'Tranche d\'âge',
            'required' => false,
            'placeholder' => '---',
            'choices' => array_flip([
                '16_24' => '16-24',
                '25_35' => '25-35',
                '36_44' => '36-44',
                '45_99' => '45+'
            ])
        ]);
        $formBuilder->add('anciennete', ChoiceType::class, [
            'label' => 'Ancienneté',
            'required' => false,
            'placeholder' => '---',
            'choices' => array_flip([
                '0_5' => '0-5',
                '6_15' => '6-15',
                '16_99' => '16 et plus'
            ])
        ]);
        $formBuilder->add('annee', IntegerType::class, ['label' => 'Année']);
        $formBuilder->add('mois', ChoiceType::class, ['choices' => array_flip(Utils::MOIS), 'label' => 'Mois', 'attr' => ['class' => 'has-select2']]);
        $formBuilder->add('communaute', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'Type de contrat',
            'class' => Communaute::class,
            'required' => false
        ]);
        $formBuilder->add('genre', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'code',
            'label' => 'Sexe',
            'class' => Genre::class,
            'required' => false
        ]);
        $formBuilder->add('unite', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'Unité',
            'class' => UniteEmploye::class,
            'required' => false
        ]);
        $formBuilder->add('niveauHierarchique', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'Niveau Hiérarchique',
            'class' => NiveauHierarchique::class,
            'required' => false
        ]);
        $formBuilder->add('niveauMaitrise', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'Niveau de maitrise',
            'class' => NiveauMaitrise::class,
            'required' => false
        ]);
        $formBuilder->add('statut', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'Statut',
            'class' => StatutEmploye::class,
            'required' => false
        ]);

        return $formBuilder->getForm();
    }

##################################################################################################################
#########################################################  Audiences de statitiques###############################
    


    #[Route('/type-contrat', name: 'app_rh_dashboard_type_contratau')]
    public function indexTypeContratau(Request $request)
    {

        $formBuilder = $this->createFormBuilder()
            ->setAction($this->generateUrl('app_rh_dashboard_type_contratau'))
            ->setMethod('POST');
        $formBuilder->add('communaute', EntityType::class, [
            'placeholder' => '---',
            'choice_label' => 'libelle',
            'label' => 'La Communaute',
            'attr' => ['class' => 'has-select2'],
            'choice_attr' => function (Communaute $communaute) {
                return ['data-value' => $communaute->getLibelle()];
            },
            'class' => Communaute::class,
            'required' => false
        ]);

        $formBuilder->add('debut', DateType::class, [
            "label" => "Date de debut*",
            "required" => true,
            "widget" => 'single_text',
            "input_format" => 'Y-m-d',
            "by_reference" => true,
            "empty_data" => '',
            'attr' => [
                'class' => 'date',
                'placeholder' => 'Date de debut'
            ]
            ]);
        
        $formBuilder->add('fin', DateType::class, [
            "label" => "Date de fin*",
            "required" => true,
            "widget" => 'single_text',
            "input_format" => 'Y-m-d',
            "by_reference" => true,
            "empty_data" => '',
            'attr' => [
                'class' => 'date',
                'placeholder' => 'Date de fin'
            ]
            ]);



        $form = $formBuilder->getForm();


       
       

        return $this->renderForm('config/statistique/Audiences/type_contrat.html.twig', [
            'form' => $form,
            
        ]);
    }
    
    #[Route('/data-type-contrat', name: 'app_rh_dashboard_type_contrat_dataau', condition: "request.query.has('filters')")]
    public function dataTypeContratau(Request $request, StatsService $statsService,DataTableFactory $dataTableFactory)
    {
        $all = $request->query->all();
        dd($all);
      
        $filters = $all['filters'] ?? [];
        $typeContratId = $filters['communaute'];
        $debut = $filters['debut'];
        $fin = $filters['fin'];

        $table = $dataTableFactory->create()
            ->add('daterencontre', DateTimeColumn::class, [
                'label' => 'Date de la rencontre',
                "format" => 'd-m-Y'
            ])
            ->add('communaute', TextColumn::class, ['label' => 'Communauté', 'field' => 'co.libelle'])
            ->add('nomchef', TextColumn::class, ['label' => 'Nom du chef'])
            ->add('numero', TextColumn::class, ['label' => 'Numéro'])
            ->add('motif', TextColumn::class, ['label' => 'Motif'])
            // ->add('email', TextColumn::class, ['label' => 'Email'])
            ->createAdapter(ORMAdapter::class, [
                'entity' => Demande::class,
                'query' => function (QueryBuilder $req) use ($typeContratId, $debut, $fin) {
                    $req->select('a,co')
                        ->from(Audience::class, 'a')
                        ->leftJoin('a.communaute', 'co')
                        ->orderBy('a.daterencontre', 'DESC')
                        ->andWhere('a.etat = :status')
                        ->andWhere('a.CreatedAt >= :debut')
                        ->andWhere('a.CreatedAt <= :fin')
                        ->andWhere('co.id = :id')
                        ->setParameter(':debut', $debut)
                        ->setParameter(':fin', $fin)
                        ->setParameter('id', $typeContratId)
                        ->setParameter('status', 'audience_valider');
                }
            ])
            ->setName('dt_app_gestion_audience');

        $renders = [
            'edit' =>  new ActionRender(function () {
                return true;
            }),
            'delete' => new ActionRender(function () {
                return true;
            }),
        ];


        $hasActions = false;

        foreach ($renders as $_ => $cb) {
            if ($cb->execute()) {
                $hasActions = true;
                break;
            }
        }

        if ($hasActions) {
            $table->add('id', TextColumn::class, [
                'label' => 'Actions', 'orderable' => false, 'globalSearchable' => false, 'className' => 'grid_row_actions', 'render' => function ($value, Audience $context) use ($renders) {
                    $options = [
                        'default_class' => 'btn btn-xs btn-clean btn-icon mr-2 ',
                        'target' => '#exampleModalSizeLg2',

                        'actions' => [
                            'edit' => [
                                'url' => $this->generateUrl('app_gestion_audience_edit', ['id' => $value]), 'ajax' => true, 'icon' => '%icon% bi bi-pen', 'attrs' => ['class' => 'btn-default'], 'render' => $renders['edit']
                            ],
                            'delete' => [
                                'target' => '#exampleModalSizeNormal',
                                'url' => $this->generateUrl('app_gestion_audience_delete', ['id' => $value]), 'ajax' => true, 'icon' => '%icon% bi bi-trash', 'attrs' => ['class' => 'btn-main'],  'render' => $renders['delete']
                            ]
                        ]

                    ];
                    return $this->renderView('_includes/default_actions.html.twig', compact('options', 'context'));
                }
            ]);
        }


        $table->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }



    //     $data =   $statsService->getAudienceMoisComNo($typeContratId,$debut,$fin);
    //     $data1 = $statsService->getAudienceMoisComYes($typeContratId,$debut,$fin);

    //     $dataan =   $statsService->getAudienceAnneeComNo($typeContratId, $debut, $fin);
    //     $data1ann = $statsService->getAudienceAnneeComYes($typeContratId, $debut, $fin);

templates/config/statistique/Repportages/indexdemandes.html.twig
{# {% extends 'base-layout.html.twig' %}

{% block title %}Liste des communautes{% endblock %}
{% block header %}communautes{% endblock %}
{% block breadcrumb %}{% endblock %} #}
{% block body %}
<div class="card shadow-sm">
  <div class="row">
    <div class="col-12">
        <ul class="nav nav-tabs nav-line-tabs mb-5 fs-6">
            <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" href="#kt_tab_pane_7">Accordés</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#kt_tab_pane_8">Réjetés</a>
            </li>
            {# <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#kt_tab_pane_9">Link 3</a>
            </li> #}
            
        </ul>
        
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="kt_tab_pane_7" role="tabpanel">
                <div class="card shadow-sm">
                    <div class="card-header card-header-sm">
                        <h3 class="card-title"> Liste des audiences avec un seul personne unique acccords</h3>
                        <div class="card-toolbar">
                            <a href="{{ path('app_pdf_generator_demende_accord') }}" class="btn btn-success btn-sm">
                                <i class="bi bi-plus-square text-light"></i>
                                imprimer la liste
                            </a>
                            &nbsp;
                
                            {# <a href="{{ path('app_parametre_communaute_new') }}" class="btn btn-main btn-sm" data-bs-toggle="modal"
                                data-bs-target="#exampleModalSizeLg2">
                                <i class="bi bi-plus-square text-light"></i>
                                Nouveau
                            </a> #}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                            <div class="table-responsive">
                                <table class="table table-striped gy-7 gs-7">
                                    <thead class="bg-primary">
                                        <tr class="fw-semibold fs-6 text-gray-800 border-bottom border-gray-200 ">
                                            <th class="text-white">Nom et prénom(s)</th>
                                            <th class="text-white">Numéro</th>
                                            <th class="text-white">Date de rencontre</th>
                                            <th class="text-white">Lieu de provénance</th>
                                
                                
                                            {# <th class="text-white">Nombre de participant</th> #}
                                            {# <th class="text-white">Communaute</th> #}
                                            <th class="text-white">Localité</th>
                                            {# <th class="text-white">Motif</th>
                                            <th class="text-white">Status de l'Audience</th> #}
                                            {# <th class="text-white">Date de création</th>
                                            <th class="text-white">Date de la dernière modtification</th> #}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for demande in stats.getDemanderealieyes %}
                                        <tr>
                                            <td>{{ demande.nom }}</td>
                                            <td>{{ demande.numero }}</td>
                                            <td>{{ demande.daterencontre ? demande.daterencontre|date('d-m-Y ') : '' }}</td>
                                            <td>{{ demande.lieuHabitation }}</td>
                                
                                            {# <td>{{ demande.nombreparticipant }}</td> #}
                                            {# <td>{{ demande.communaute.libelle | lower}}</td> #}
                                            <td>{{ demande.communaute.localite.libelle | lower }}</td>
                                            {# <td>{{ demande.observation }}</td> #}
                                            {# <td>{{ demande.motif }}</td>
                                            <td>{{ demande.statusdemande ? 'Yes' : 'No' }}</td> #}
                                            {# <td>{{ demande.CreatedAt ? demande.CreatedAt|date('d-m-Y ') : '' }}</td>
                                            <td>{{ demande.UpdatedAt ? audience.UpdatedAt|date('d-m-Y ') : '' }}</td> #}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="card shadow-sm">
                
            </div>
            </div>
            <div class="tab-pane fade" id="kt_tab_pane_8" role="tabpanel">
                <div class="card shadow-sm">
                    <div class="card-header card-header-sm">
                        <h3 class="card-title"> Liste des audiences avec un seul personne unique rejetées</h3>
                        <div class="card-toolbar">
                            <a href="{{ path('app_pdf_generator_demande_rejet') }}" class="btn btn-success btn-sm">
                                <i class="bi bi-plus-square text-light"></i>
                                imprimer la liste
                            </a>
                            &nbsp;
                
                            {# <a href="{{ path('app_parametre_communaute_new') }}" class="btn btn-main btn-sm" data-bs-toggle="modal"
                                data-bs-target="#exampleModalSizeLg2">
                                <i class="bi bi-plus-square text-light"></i>
                                Nouveau
                            </a> #}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table table-striped gy-7 gs-7">
                                        <thead class="bg-primary">
                                            <tr class="fw-semibold fs-6 text-gray-800 border-bottom border-gray-200 ">
                                                <th class="text-white">Nom et prénom(s)</th>
                                                <th class="text-white">Numéro</th>
                                                <th class="text-white">Date de rencontre</th>
                                                <th class="text-white">Lieu de provénance</th>
                
                
                                                {# <th class="text-white">Nombre de participant</th> #}
                                                {# <th class="text-white">Communaute</th> #}
                                                <th class="text-white">Localité</th>
                                                {# <th class="text-white">Motif</th>
                                                <th class="text-white">Status de l'Audience</th> #}
                                                {# <th class="text-white">Date de création</th>
                                                <th class="text-white">Date de la dernière modtification</th> #}
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for demande in stats.getDeamnderealieno %}
                                                <tr>
                                                    <td>{{ demande.nom }}</td>
                                                    <td>{{ demande.numero }}</td>
                                                    <td>{{ demande.daterencontre ? demande.daterencontre|date('d-m-Y ') : '' }}</td>
                                                    <td>{{ demande.lieuHabitation }}</td>
                                                    {# <td>{{ demande.nombreparticipant }}</td> #}
                                                    {# <td>{{ demande.communaute.libelle | lower}}</td> #}
                                                    <td>{{ demande.communaute.localite.libelle | lower }}</td>
                                                    {# <td>{{ demande.observation }}</td> #}
                                                    {# <td>{{ demande.motif }}</td>
                                                    <td>{{ demande.statusdemande ? 'Yes' : 'No' }}</td> #}
                                                    {# <td>{{ demande.CreatedAt ? demande.CreatedAt|date('d-m-Y ') : '' }}</td>
                                                    <td>{{ demande.UpdatedAt ? audience.UpdatedAt|date('d-m-Y ') : '' }}</td> #}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
            </div>
            {# <div class="tab-pane fade" id="kt_tab_pane_9" role="tabpanel">
                ...
            </div>
            <div class="tab-pane fade show active" id="kt_tab_pane_10" role="tabpanel">
                ...
            </div>y
            <div class="tab-pane fade" id="kt_tab_pane_11" role="tabpanel">
                ...
            </div>
            <div class="tab-pane fade" id="kt_tab_pane_12" role="tabpanel">
                ...
            </div>
            <div class="tab-pane fade" id="kt_tab_pane_13" role="tabpanel">
                ...
            </div> #}
        </div>
    </div>
  </div>
 
</div>
{% endblock %}


{% block java %}

{% endblock %}